### ISSUE TITLE
Error message when running  model.SSA()  and  model.multiagent()

### ISSUE THREAD

**Issue by tbose1** [DiODeProject/MuMoT#100]
AttributeError: 'Dropdown' object has no attribute 'layout'

I tried to update ipywidgets in the conda environment I'm using on my local machine but this caused updates of other packages as well due to dependencies which then disabled all widgets in the notebook. I downgraded to my previous version of ipywidgets again.

Currently I'm using ipywidgets=4.1.1 and notebook=4.1.0 package versions. 

We should find a configuration that works for everyone.

**Comment by willfurnass** [comment]
Could switch to using setup.py to define essential requirements (except LaTeX and graphviz) and we'd then have a single env for testing and deployment (local, Travis, Binder).  Requires that #158 be resolved.
