### ISSUE TITLE
latest versions of dependent packages cause problems with MuMoT figures

### ISSUE THREAD

**Issue by joefresna** [DiODeProject/MuMoT#108]
When updating all packages, manual configuration of `PyDSTool` is necessary (because otherwise it won't work with `SciPy 1.0.0`) 
https://stackoverflow.com/questions/48251201/import-of-package-pydstool-doesnt-work
In particular, it's necessary to modify two files:
`lib/python3.5/site-packages/PyDSTool/__init__.py` (line 75):
change
```
if vernums[1] < 5:
```
in
```
if vernums[0] < 1 and vernums[1] < 5:
```
and file `lib/python3.5/site-packages/PyDSTool/parseUtils.py` (line 46-47), change:
```
'h2vp', 'sph_jn', 'sph_yn', 'sph_jnyn', 'sph_in',
'sph_kn', 'sph_inkn', 'riccati_jn', 'riccati_yn',
```
to
```
'h2vp', 'spherical_jn', 'spherical_yn', 'spherical_in',
'spherical_kn', 'riccati_jn', 'riccati_yn',
```

After the update, the dependent libraries in their last version causes problems to MuMoT figures:
* Plot size is small
* A new figure is drawn each time a widget is changed (instead of updating the same figure)

**Comment by willfurnass** [comment]
Fixed via #338
