### ISSUE TITLE
Python docstrings

### ISSUE THREAD

**Issue by jarmarshall** [DiODeProject/MuMoT#112]
I've started work towards using docstrings for description of user-visible functions, initially, suitable for user help using the `help()` function while working in a notebook. See the user manual for an example, and the `stream` and `vector` function definitions for examples of the template I want us to use.

Hopefully @willfurnass can help us with setting up auto-build of the docs with Sphinx and publication to [ReadTheDocs](https://readthedocs.org)

**Comment by willfurnass** [comment]
As of PR #168 Sphinx can generate API docs from numpydoc-formatted docstrings.  I've added a number of examples of numpydoc-style docstrings to the package's main module but there are still quite a few classes and methods that lack docstrings.  Others with greater knowledge of the codebase will need to supply these.

**Comment by willfurnass** [comment]
Please can @joefresna @jarmarshall and@tbose1 fill in missing parameter and return types in docstrings (search for docstrings containing "`object` " and/or "`type?`")

**Comment by tbose1** [comment]
Added class docstring for `MuMoTbifurcationView` and return types as indicated in the checklist above via 7629371c5d890de251cdffd6389b3aca2add784c.

**Comment by jarmarshall** [comment]
Also need to:

- [ ] change from docstring format for `_round_to_1(x)` so it does not show up in the Sphinx documentation (this is the only hidden function to be so-documented)

**Comment by jarmarshall** [comment]
`setView()` removed as being renamed to `_setView()` (see issue #304)

**Comment by jarmarshall** [comment]
docstring format for `_round_to_1()` not relevant as it is being removed from `api.rst` (see issue #306)
