### ISSUE TITLE
MuMoTstochasticSimulationControllers don't show the greek letters reactants in the widget properly

### ISSUE THREAD

**Issue by joefresna** [DiODeProject/MuMoT#128]
To follow the `integrate` implementation

**Comment by jarmarshall** [comment]
Is this definitely closed? `multiAgent()` is now resulting in what seems to be the same error for me. `SSA()` is fine though.

**Comment by joefresna** [comment]
I cannot see this problem... Do you have an example for it?

**Comment by jarmarshall** [comment]
Seems fine now
