### ISSUE TITLE
SSA and multiagent print bookmarks to logs for every new run

### ISSUE THREAD

**Issue by jarmarshall** [DiODeProject/MuMoT#138]
This is confusing behaviour for the user and inconsistent with how other views behave.

**Comment by joefresna** [comment]
It wasn't a bookmark but the standalone view command  to allow the user to run the view without controller (issue #92)

**Comment by jarmarshall** [comment]
OK, I don't think it should happen though - there is bookmark functionality which is very similar - more useful to bookmark interesting parameter values than have everything output automatically then struggle to find the points of interest

**Comment by joefresna** [comment]
Solved by commit https://github.com/DiODeProject/MuMoT/commit/dfce8ad7e7519199bc681a0b8647c21634ba71d5 (which used wrong issue number...)
