### ISSUE TITLE
Enable Travis CI for this repo

### ISSUE THREAD

**Issue by willfurnass** [DiODeProject/MuMoT#154]
I don't have admin rights for this repo so can't do it myself.  @jarmarshall - can you?  You need to visit https://travis-ci.com/DiODeProject/MuMoT/, log in using GitHub credentials then click *Activate*.

**Comment by willfurnass** [comment]
Done as of  c9afa6ac342b1305e81428b2e94a8b13d39c56d4

**Comment by willfurnass** [comment]
Let's switch from (a trial of) travis-ci.com to (free for FOSS) travis-ci.org.  @jarmarshall you should get another authorisation request re this.

**Comment by jarmarshall** [comment]
As far as I can tell this has access now, but I didn’t do anything...

**Comment by willfurnass** [comment]
What do you get if you browse to https://travis-ci.org/DiODeProject/MuMoT/ (NB .org, not .com)?

**Comment by joefresna** [comment]
sorry, I authorised it yesterday.

**Comment by jarmarshall** [comment]
I think I've just authorised it too - certainly when I use @willfurnass ' link I log in to Travis and sync my account successfully...

**Comment by willfurnass** [comment]
Ta; working again.
