### ISSUE TITLE
Generate code coverage reports

### ISSUE THREAD

**Issue by willfurnass** [DiODeProject/MuMoT#157]
In the first instance can generate interactively using [pytest-cov](https://pytest-cov.readthedocs.io/en/latest/) and [tox](https://github.com/tox-dev/tox), then can move on to automating the measuring of code coverage using [Travis CI](https://travis-ci.org/) and [CodeCov](https://codecov.io/).

**Comment by willfurnass** [comment]
Tried enabling code coverage report generation and uploading to codecov.io in PR #178 and 57f9928d3d6201dc56dbb92e2a75b31791539b04.  The Travis CI build logs show code coverage report sent to stdout but attempts to upload report to codecov.io fail:

```
The command "tox" exited with 0.
0.27s$ bash <(curl -s https://codecov.io/bash)
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-0b37652
==> Travis CI detected.
    project root: .
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
==> Running gcov in . (disable via -X gcov)
==> Python coveragepy not found
==> Searching for coverage reports in:
    + .
--> No coverage report found.
    Please visit http://docs.codecov.io/docs/supported-languages
The command "bash <(curl -s https://codecov.io/bash)" exited with 0.
Done. Your build exited with 0.
```

Was the code coverage report written to disk by `pytest-cov`?  Or was it written to a dir not checked by the codecov report uploader?

**Comment by jarmarshall** [comment]
A colleague has deployed this successfully on their GitHub repository I think - shall I ask for some further information?

**Comment by willfurnass** [comment]
@jarmarshall Thanks, might expedite things.

**Comment by neworderofjamie** [comment]
Hi @willfurnass - I am that college! Our current project is C++-based so we're using gcov to generate our coverage data meaning that things are a little different. However you should definitely be writing your coverage data to a file rather than stdout and, if the codecov script still isn't finding it, you can also manually point the script at your coverage data. For example we do this:
``curl -s https://codecov.io/bash | bash -s - -f combined_coverage.txt -t OUR_MAGICAL_TOKEN``
Where, as I remember, the -f forces codecov to look at a specific file.

**Comment by jarmarshall** [comment]
Thanks @neworderofjamie - does that help @willfurnass ?

**Comment by willfurnass** [comment]
Thanks @neworderofjamie; I'm getting a `.coverage` file generated when I run the test+coverage suite locally so I'm not sure why the codecov uploader isn't picking this up; I'll add a check to our travis config for the existence of `.coverage` at the end of a travis job.  BTW it's good to see an example of uploading a file containing combined coverage data; that will likely be useful for this project in future for amalgamating data from unit and integration/regression tests.

**Comment by willfurnass** [comment]
Code coverage for the (stub of) unit test suite ([tests/test_all.py](tests/test_all.py)) now measured and pushed to codecov.io: https://codecov.io/gh/DiODeProject/MuMoT.

**Comment by willfurnass** [comment]
Can't generate code coverage with

```
pytest --cov={envsitepackagesdir}/mumot --maxfail=1 --nbval-lax --nbdime TestNotebooks/MuMoTtest.ipynb
```

as when pytest+nbval are run with coverage support enabled the explicit references to cell numbers are incorrect.  Addressing #156 may help with this.

**Comment by willfurnass** [comment]
Coverage is still fairly low but I think the reporting is working now.  Closing.

**Comment by jarmarshall** [comment]
@willfurnass if we can get code coverage working off notebooks as well (see issue #108 ?) this number should increase - in the short term, that would be preferred as we're short of time to write proper unit tests before publication...

**Comment by willfurnass** [comment]
https://github.com/DiODeProject/MuMoT/blob/master/tox.ini

**Comment by willfurnass** [comment]
I think not; reopen if you disagree.
