### ISSUE TITLE
Superfluous matplotlib figures shown

### ISSUE THREAD

**Issue by willfurnass** [DiODeProject/MuMoT#158]
Various statements in the MuMoTtest.ipynb Notebook result in bare, superfluous Figure objects being displayed before the Figures that those statements should produce.  An example statement is: 

```python
bookmark1 = model4.bifurcation('s', 'A-B', initialState = {'U': 0.0, 'A': 1.0, 'B': 0.0}, initBifParam = 2.0, params = [('\\mu', 2.0), ('\\Delta', 2.0), ('plotLimits', 1), ('systemSize', 1)], initWigdets = {'\\mu': [3, 1.1, 5, 0.1], '\\Delta': [0.1, 0, 5, 0.1]}, bookmark = False)
```

Could there be a superfluous call to `matplotlib.pyplot.figure()` somewhere?

More info:
```
pip freeze | grep -E 'matplotlib|ipython|notebook'                                                                                                                                   
ipython==6.4.0                                                                                                                                                                               
ipython-genutils==0.2.0                                                                                                                                                                      
matplotlib==2.2.2                                                                                                                                                                            
notebook==5.6.0
```
Noticed using commit af774f512e9657f39f53ca0ceab57de82ed8bd83

**Comment by willfurnass** [comment]
Nope, just the mandatory dependencies inc minimum versions listed in [setup.py](setup.py).  Know what fixed this previously?  Had a look for pertinent GH Issues but didn't find anything.  

NB continuous integration runs currently install MuMoT plus dependencies in a virtualenv using the package info in setup.py; I could change this to use conda but want the dependency info in setup.py to be right, as that defines what's absolutely required to get expected functionality.

**Comment by jarmarshall** [comment]
@joefresna @tbose1 do you recall?

**Comment by willfurnass** [comment]
Yes, likely.  I tried forcing matplotlib, ipywidgets and sympy versions in setup.py so they matched those in environment.yml but that didn't help.

**Comment by jarmarshall** [comment]
Running a build from today via MyBinder does not exhibit this problem, as far as I can see...

**Comment by willfurnass** [comment]
MyBinder uses the conda `environment.yml`.  The problem seems to be with a virtualenv created with the minimal set of essential dependencies defined in `setup.py`.

**Comment by willfurnass** [comment]
@tbose1 Can you add a docstring for `_buildFig` explaining what the function does.

**Comment by tbose1** [comment]
Added docstring to `buildFig` in commit eb90d059e8d14beacbbe924142a392ea263a9b21.

**Comment by jarmarshall** [comment]
The environments created via pip and conda differ markedly in the library versions installed - not being expert in pip or conda I am not sure of how to ensure consistency - I have briefly tried downgrading matplotlib, ipython, and ipywidgets to the versions in `environment.yml` - this failed to solve the problem and created new problems. Is there an elegant way of copying a minimal working environment to `requirements.txt` @willfurnass ?

**Comment by willfurnass** [comment]
Here's a [*maximal* working `requirements.txt`](https://github.com/DiODeProject/MuMoT/files/2469087/requirements.txt).  Not yet had chance to pick apart which package(s)/versions are required to avoid the duplicate figure issue...

**Comment by jarmarshall** [comment]
I'm a bit confused now - is `requirements.txt` deprecated, and all requirements should go in `setup.py`?

**Comment by jarmarshall** [comment]
I've found the old issue this cropped up in (#108)
I've copied those requirements in full into `setup.py` in my branch https://github.com/jarmarshall/MuMoT
There are various build errors, and then a notebook error that looks familiar, but I can't find the relevant issue:

```TraitError: The 'selected_index' trait of an Accordion instance must be an int, but a value of None <class 'NoneType'> was specified.```

@willfurnass it seems we're just chasing our tails now trying to get virtualenv working - you said you could change the continuous integration to work with conda - I think we should do that and only support conda installation at this point.

**Comment by jarmarshall** [comment]
I've noticed something else - in the virtualenv installation figures are no longer in interactive mode (pannable, etc.) - this may be related - have tried installing ipympl and using the `matplotlib widget` magic but this hasn't made a difference - want to check if the conda installation is still in interactive mode but the MyBinder site has just spent 10 minutes failing to build...

**Comment by jarmarshall** [comment]
Having checked the conda installation and MyBinder deployment too, both work in interactive mode for plots correctly - by contrast the virtualenv approach does not, and I think this is the root of this issue. It seems that virtualenvs may not play nicely with matplotlib, e.g. see https://matplotlib.org/faq/virtualenv_faq.html (although not sure when that was written) - I recommend we only support the conda installation route and change the continuous integration over to use this @willfurnass

**Comment by tbose1** [comment]
Installation of MuMoT within the `mumot-env` conda environment following the documentation brings back the superfluous figure problem on my system (macOS), i.e. each time a slider is changed a new figure appears below the previous one. Also the rendering of the figures is affected. This is probably due to pinning `matplotlib` to a version `<3.0` which currently installs `matplotlib=2.2.3`. Pinning the version to  `matplotlib=2.1.2` seems to solve this problem. The most recent version is `3.0.2` but this appears to be incompatible with other dependencies.

**Comment by tbose1** [comment]
Update: pinning `matplotlib` to another version doesn't help. I'm working on another solution.

**Comment by tbose1** [comment]
Solved with commit 97e10743028d826b2ec48fa42731bfa8a1f96c22. Added the following to the MuMoT code (chooses TkAgg backend if mac-user):

if sys.platform == "darwin": #if operating system is macOS
    import matplotlib
    matplotlib.use('TkAgg')

**Comment by willfurnass** [comment]
@tbose1 I suggest also adding comments above those three lines to explain why they're needed.

**Comment by tbose1** [comment]
Added comments via 6d9520c4a9d200d826e2c64b06429a7a573832ca.
