### ISSUE TITLE
Get working with mybinder.org and document

### ISSUE THREAD

**Issue by willfurnass** [DiODeProject/MuMoT#161]
I've made the repo public and created a `binder-compat` branch for this.  This branch includes:
- A modified `environment.yml` that definitely works on Linux 
- Extra files (`apt.txt` and `postBuild`) for ensuring that a LaTeX distro and graphviz are installed and the LaTeX fontcache is generated. 

@jarmarshall @joefresna @tbose1: You can test this with the User Manual [here](https://mybinder.org/v2/gh/DiODeProject/MuMoT/binder-compat?filepath=docs%2FMuMoTuserManual.ipynb)

Note: mybinder.org builds a new Docker container for each commit, which takes ~10 mins, then pushes these to its image registry (cache) for use by other users / in other sessions.

**Comment by jarmarshall** [comment]
Fantastic! Is it possibly to add `toc2` from `jupyter_nbextensions` to the Docker build so the table of contents can be built?

**Comment by willfurnass** [comment]
@jarmarshall Yep, I've added the following to [postBuild](postBuild) and toc2 is now enabled automatically.  I've also updated the TOC2 setup instructions in [README.md](README.md) as they weren't quite right.

```sh
jupyter contrib nbextension install --sys-prefix
jupyter nbextension enable toc2/main
```

**Comment by jarmarshall** [comment]
Brilliant!

**Comment by jarmarshall** [comment]
One other note - it would be good to have the checked-in version of the user manual always have empty content cells, otherwise users will get confused by the various error messages, and will have to restart the kernel...

**Comment by willfurnass** [comment]
Done.
