### ISSUE TITLE
Specify the environment.yml for your OS

### ISSUE THREAD

**Issue by joefresna** [DiODeProject/MuMoT#196]
Installation step 4 should specify that the user must use the correct environment.yml for the used Operating System:
* `environment.yml`
* `environment_macos.yml`
* `environment_win.yml`

**Comment by willfurnass** [comment]
@joefresna Fancy trying adding that to `docs/source/install.rst`?

**Comment by joefresna** [comment]
ok, I can do it once I solve the issue #195 (i.e. I successfully install the latest version)

**Comment by jarmarshall** [comment]
I think when pull request #210 is merged this issue can be closed, as all the `.yml` files will have been removed.

**Comment by jarmarshall** [comment]
Closed by PR #210
