### ISSUE TITLE
stream plot not working properly for simple models

### ISSUE THREAD

**Issue by joefresna** [DiODeProject/MuMoT#202]
After the block of commits https://github.com/DiODeProject/MuMoT/commit/68a463f423e5f9280ff962649ccbfbdf9843ec2f to https://github.com/DiODeProject/MuMoT/commit/1a7c9be394439cb0f075d33e6ac8889d23907c6e (Jun 1 to 5), the function `stream()` does not work for the simple model proposed in the attached example.
[Issue_stream.zip](https://github.com/DiODeProject/MuMoT/files/2480493/Issue_stream.zip)

**Comment by jarmarshall** [comment]
@tbose1 looks like this is indeed your code?

**Comment by tbose1** [comment]
Solved with commit 6df9a15590a287790b21100095c93de38c76e643
