### ISSUE TITLE
Add methods to access mathematical expression objects

### ISSUE THREAD

**Issue by jarmarshall** [DiODeProject/MuMoT#211]
Getter methods should be added to access ODE expression objects, Master Equation, van Kampen, Fokker-Planck, etc.

**Comment by jarmarshall** [comment]
see also issue #9

**Comment by jarmarshall** [comment]
@joefresna how do you think this functionality should work? Is the existing implementation intended to provide a hyperlink to download the file?

**Comment by jarmarshall** [comment]
Last two comments moved to issue #9 where they belong - bug label removed

**Comment by jarmarshall** [comment]
Reopening issues for @tbose1 's comments to avoid us forgetting about this - please see checklist in PR #233

**Comment by tbose1** [comment]
Checked all getter methods which all work as they should. Made some changes to Python docstrings of getter functions via 944835a1880c368669e12b7a154570d72e869402.
