### ISSUE TITLE
Split MuMoTtest.ipynb

### ISSUE THREAD

**Issue by jarmarshall** [DiODeProject/MuMoT#236]
Having a monolith notebook may be causing issues with Travis continuous integration (e.g. see pull request #234)

Also, run interactively the following warning is displayed once in section 10:

> //anaconda/envs/MumotEnv/lib/python3.5/site-packages/matplotlib/pyplot.py:524: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  max_open_warning, RuntimeWarning)

**Comment by willfurnass** [comment]
Enabling verbose pytest output shows an exception/error is raised by cell 45 of the user manual; from [a travis-ci.org build log](https://travis-ci.org/DiODeProject/MuMoT/builds/466928400?utm_source=github_status&utm_medium=notification):

```
docs/MuMoTuserManual::ipynb::Cell 45 FAILED                              [ 83%]
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

Couldn't reproduce this with a local tox run; needs more investigation.

**Comment by jarmarshall** [comment]
That's odd - cell %45 should be simply showing a log file - this does contain some LaTeX characters, but these have previously worked. I can see no other reason for it to fail at this point.

**Comment by willfurnass** [comment]
I think the suspicions in my previous comment were correct (but the details weren't): 

I've been playing with the `master` of a fresh clone; think the issue is an incorrect explicit cell ref in the user manual resulting in the variable `model7` being `None` rather than a model.

```
AttributeError                            Traceback (most recent call last)
<ipython-input-46-73f6a20df767> in <module>
----> 1 model7.showMasterEquation()

AttributeError: 'NoneType' object has no attribute 'showMasterEquation' 
```

I suspect content has been added to the user manual notebook but the explicit cell ref used to instantiate `model7` later on in the Notebook wasn't then updated.  (See also Issue #156).

Should hopefully be addressed by PR 240.

Separately, I think it would be sensible if `parseModel` returned an error/exception or generated a warning if parsing fails (Issue #241).

**Comment by jarmarshall** [comment]
Great, thanks for chasing this down... I've self-assigned #241 and will try to implement ASAP
PS I didn't appreciate the user manual was in the test suite - please can you point to where the test notebooks are specified for Travis?

**Comment by willfurnass** [comment]
> PS I didn't appreciate the user manual was in the test suite - please can you point to where the test notebooks are specified for Travis?

@jarmarshall See the `commands` section of `tox.ini`

**Comment by willfurnass** [comment]
@jarmarshall Do you think this can be closed now?  I don't think splitting the main test notebook into multiple notebooks will make CI jobs run any quicker (at least without looking further into whether we can enable any parallelisation using tox + travis-ci.org) and it's not a blocker for the first release.

**Comment by jarmarshall** [comment]
OK, happy to close for now - I do not think it's a speed issue as much as a memory issue - I worry that a single monolith notebook may fail at some point because of the number of open figures. But if it works for now let's stick with it for now...
