### ISSUE TITLE
build:passing icon misleading?

### ISSUE THREAD

**Issue by jarmarshall** [DiODeProject/MuMoT#238]
The build:passing icon shows even though recent merges (e.g. PRs #237 #234) had non-terminating CI tests - clicking on the icon indicates no recent CI tests? https://travis-ci.com/DiODeProject/MuMoT @willfurnass is this working as expected?

**Comment by willfurnass** [comment]
Whoops, that icon was generated by travis-ci.com, which is the commercial, limited service we were using before we made the repo public and switched to using travis-ci.org.  PR #239 updates the icon URL and link URL so that they relate to travis-ci.org build status/info.

**Comment by willfurnass** [comment]
Fixed
