### ISSUE TITLE
parseModel should raise an exception or generate a warning if parsing fails...

### ISSUE THREAD

**Issue by willfurnass** [DiODeProject/MuMoT#241]
...not just return `None` as this leads to confusion when the user then tries to do anything (e.g. call methods) with what they erroneously think is a `MuMoTmodel` object.

**Comment by jarmarshall** [comment]
Agreed - will look into it

**Comment by jarmarshall** [comment]
Pull request #245 creates a new warning class `MuMoTWarning` and has `parseModel()` raise this when returning `None`

**Comment by jarmarshall** [comment]
Closed by pull request #245
