### ISSUE TITLE
Improve accuracy of code coverage report

### ISSUE THREAD

**Issue by jarmarshall** [DiODeProject/MuMoT#247]
Current CodeCov reports coverage over all code, including some ancillary code not written by the project team - instead the report should just refer to coverage of core MuMoT code, if CodeCov can be configured in this way.

**Comment by willfurnass** [comment]
Suspect we want the following in `codecov.yml`:

```yaml
ignore:
  - "mumot/gen"
  - "mumot/process_latex"
```

See https://docs.codecov.io/docs/ignoring-paths

**Comment by willfurnass** [comment]
Or, more simply, more lines beneath `omit` in the existing `.coveragerc` file

**Comment by willfurnass** [comment]
Question: if 3rd-party code has been incorporated in this repo then could it be argued that this repo should also include tests for that code e.g. https://github.com/jackatbancast/latex2sympy/blob/master/test.py?

**Comment by willfurnass** [comment]
Hmm, not yet managed to get `omit` in `coveragerc` to do what I expect.  These pointers may help: https://github.com/pytest-dev/pytest-cov/issues/130

**Comment by willfurnass** [comment]
Fixed in #299 - follow link from badge in README to see list of files for which coverage is reported.
