### ISSUE TITLE
Rename round_to_1()

### ISSUE THREAD

**Issue by jarmarshall** [DiODeProject/MuMoT#250]
Rename `round_to_1()` to `_round_to_1()` so it is not publicly visible, e.g. in the API docs or on tab completion in a notebook

**Comment by tbose1** [comment]
Renaming done via 916b4b2f09642c6082b4c06b99a1e9787d81748f. NB: Renaming was also necessary in the file api.rst (to build documentation) which can be found in docs/source/.
