### ISSUE TITLE
Trim verbose bifurcation status message

### ISSUE THREAD

**Issue by jarmarshall** [DiODeProject/MuMoT#253]
If `bifurcation()` works correctly it displays a verbose multi-line status message
``Stationary state(s) detected and continuated. Initial conditions for state variables specified on sliders in Advanced options tab were not used. (Those are only used in case the calculation of fixed points fails.)``
Consider if any message during normal operation is appropriate here, rather than in the log - if yes, make shorter and simpler for non-experts to understand.

**Comment by tbose1** [comment]
This status message is now only in the logs. Change made via 916b4b2f09642c6082b4c06b99a1e9787d81748f.
