### ISSUE TITLE
TypeError when computing noise for Lotka-Volterra system

### ISSUE THREAD

**Issue by jarmarshall** [DiODeProject/MuMoT#254]
The following code results in `TypeError: Invalid NaN comparison` - could be a general error for systems only having unstable fixed points? Brusellator parameterised for single unstable fixed point works correctly (although noise is shown as symmetric, not sure if this is correct or not) but I think the nature of the fixed points may differ (certainly MuMoT represents them differently).

```
mumot.setVerboseExceptions()

%%model
$
(A) + X -> X + X : \alpha
X + Y -> Y + Y : \beta
Y -> \emptyset : \gamma
$

lv = mumot.parseModel(In[-2])

mumot.setVerboseExceptions()
stream2 = lv.stream('X', 'Y', showFixedPoints  = True, showNoise = True)
```

**Comment by tbose1** [comment]
Solved via 6d9520c4a9d200d826e2c64b06429a7a573832ca.

The NaN comparison error resulted from the failure to calculate the second order moments analytically that determine the width and height of the corresponding noise-ellipse. This resulted in one of those quantities being infinite.

When `showNoise=True` is chosen in field-based plots it works as follows now:
Try to calculate noise analytically. If analytical calculation fails try to calculate noise numerically . But if the system has no stable attracting states then numerical calculation of noise is disabled too. Warning messages will be printed above the figure in both cases (if `showNoise=True` was chosen) but the figure will be produced nevertheless (without showing noise). This prevents error messages and maintains continuous workflow.
