### ISSUE TITLE
Documentation may need update...

### ISSUE THREAD

**Issue by joefresna** [DiODeProject/MuMoT#272]
On my Mac OSX system (conda 4.5.11), the installation command from https://diodeproject.github.io/MuMoT/install.html:
`conda env create -n mumot-env python=3.6`
does not work and gives the error:
SpecNotFound: Invalid name, try the format: user/package

I needed to execute 
`conda create -n mumot-env python=3.6`

I do not know if this command would work for every system.

**Comment by jarmarshall** [comment]
Appears to have been closed by pull request #274
