### ISSUE TITLE
Bookmarking does not work in Multicontrollers

### ISSUE THREAD

**Issue by joefresna** [DiODeProject/MuMoT#279]

**Comment by jarmarshall** [comment]
The is a bit odd as it worked as of commit 9f77564b2e95ad5b6760eb69964987732d877045 ; it seems that `_print_standalone_view_cmd()` is heavily overloaded, having at least 3 forms with different arguments... this may have contributed also to issue #255

**Comment by joefresna** [comment]
Latest commit in #286 solved this issue

**Comment by joefresna** [comment]
and now (I believe for the first time ever), bookmarking also works for nested multicontrollers.
Although, it would be beneficial to enforce `silent=True` to all child views (currently not done).

**Comment by jarmarshall** [comment]
Great, thanks - saves me some work 😃 

Although I'm fairly sure nested multicontroller bookmarks have worked in the past, e.g. in mid-December, but as-yet unidentified code rot seemed to set in after that. I was testing this stuff fairly intensively!

**Comment by jarmarshall** [comment]
Good to close I think @joefresna
