### ISSUE TITLE
Field plots in multiController crash when MuMoTstochasticSimulationView keywords are specified

### ISSUE THREAD

**Issue by joefresna** [DiODeProject/MuMoT#285]
This bug appeared prior to pull requests #276 

See attached notebook for an example
[issue285.zip](https://github.com/DiODeProject/MuMoT/files/2917221/issue285.zip)

**Comment by jarmarshall** [comment]
Is this a more general point suggestion that view-creating commands should not crash when they receive unexpected keyword arguments?

**Comment by jarmarshall** [comment]
The solution is currently is to move the keywords down to the lowest level in the multicontroller at which they are meaningful, in this case within the SSA controller creation...

**Comment by jarmarshall** [comment]
Hmmm... already `stream()` ignores irrelevant keywords... e.g. ``model4.stream('\\alpha','B',foo = True)`` works...
And indeed moving those SSA-specific keywords directly into the creation of the stream view also works...
The error is that somehow these arguments are being parsed... currently no idea why...

**Comment by jarmarshall** [comment]
A bit more info - moving the `showNoise` keyword up to the multicontroller level does not cause an error - it also does not result in noise being calculated in the stream view, which I think is expected since the stream controller needs to be created before the multicontroller, hence does not see the keyword on creation.

**Comment by joefresna** [comment]
I've the feeling that solving #290 could help in some of these recent issues....

**Comment by joefresna** [comment]
Indeed, solving #290 has also fixed this :-)

**Comment by jarmarshall** [comment]
Good to close I think @joefresna
