### ISSUE TITLE
Duplicate code in MuMoTview._get_bookmarks_params() and MuMoTview._get_params() calls for bugs

### ISSUE THREAD

**Issue by joefresna** [DiODeProject/MuMoT#290]
These methods do more or less the same thing, but instead to reuse code there is a messy copy-paste...
The original idea was that `_get_bookmarks_params()` would call `_get_params() `

**Comment by jarmarshall** [comment]
I think you can close this now @joefresna - if you use `Fixes #<num1> Fixes #<num2>` in the commit message it will happen automatically (check the exact syntax for multiple issues though)

**Comment by joefresna** [comment]
I will close all issue when #286 gets accepted

**Comment by jarmarshall** [comment]
Good to close I think @joefresna
