### ISSUE TITLE
MuMoTmultiController with field plots that do not ask for extra widgets still create an empty Advanced Option menu

### ISSUE THREAD

**Issue by joefresna** [DiODeProject/MuMoT#291]
Related to #256

**Comment by jarmarshall** [comment]
This is a downside of having the new widgets for field views in advanced widgets (#285 ?) - no other views with advanced widgets can have none present, hence logic is not currently in place to deal with this.

**Comment by joefresna** [comment]
This is solved in #286 (when accepted I will close this)

**Comment by jarmarshall** [comment]
Sorry, I forgot I still need to review the pull request...
