### ISSUE TITLE
Clean up old branches

### ISSUE THREAD

**Issue by willfurnass** [DiODeProject/MuMoT#297]
There are a number of old branches in this repo.  Branches that have been merged into `master` are of no value and can be identified with:

```sh
git fetch --prune --all --tags
git branch -a --merged upstream/master | grep upstream | grep -v master
```

These can be subsequently deleted with:

```sh
git branch -a --merged upstream/master | grep upstream | grep -v master | xargs git push --delete upstream
```

I recommend deleting branches following the merging of a Pull Request unless there is good reason to do so.

**Comment by jarmarshall** [comment]
Tried this but
```git branch -a --merged upstream/master | grep upstream | grep -v master```
returned error
```fatal: malformed object name upstream/master```

**Comment by jarmarshall** [comment]
For now I've manually deleted merged and stale branches via the GitHub interface
