### ISSUE TITLE
Switch to using LaTeX to Sympy parsing now offered by Sympy? 

### ISSUE THREAD

**Issue by willfurnass** [DiODeProject/MuMoT#300]
- See https://github.com/sympy/sympy/pull/13706
- Available in sympy >= 1.3
- Unlike the 3rd party code added to the MuMoT repo, this code is tested (see also #246)!
- NB the key new function in sympy is `parse_latex` (not `process_sympy`, as defined in the `process_latex` module of the MuMoT package)

*However*, we can't switch to using sympy 1.3 as MuMot is not yet compatible with it (see #170)

**Comment by jarmarshall** [comment]
Seems like a good plan but probably the whole issue of pinned versions will need to be resolved at the same time, due to likely dependencies conflicts.

**Comment by jarmarshall** [comment]
Having ascertained that Sympy is actually incorporating the latex2sympy parser, this makes perfect sense now that PR #344 has been closed. @willfurnass you OK to make the switch?

**Comment by jarmarshall** [comment]
I believe this can be closed as of PR #348 , @willfurnass ?

**Comment by willfurnass** [comment]
Yep.
