### ISSUE TITLE
Note that need to explicitly push tags in docs on making releases 

### ISSUE THREAD

**Issue by willfurnass** [DiODeProject/MuMoT#315]
See 'sharing tags' in https://git-scm.com/book/en/v2/Git-Basics-Tagging.

Issue discovered in #312 by @jarmarshall

**Comment by jarmarshall** [comment]
Thanks @willfurnass - `push` is already in the docs - is it a `commit` step that is missing? I am not familiar enough with tags to understand the use case, but it seems the branch needs to be committed to be visible.

**Comment by willfurnass** [comment]
You need to make sure you explicitly push the tag by name to GitHub.  

Ah, this appears to already have been done:

https://github.com/DiODeProject/MuMoT/tree/v1.0.0

**Comment by jarmarshall** [comment]
but I think we need to add instructions to commit the release branch to GitHub...?

**Comment by jarmarshall** [comment]
Ah, now I see that the `commit` step was there all along, but I think pushing tags doesn't push the branch, and an additional step is needed (e.g. see https://wincent.com/wiki/Pushing_branches_and_tags_with_a_single_%22git_push%22_invocation)

Will fix this in closing issue #316
