### ISSUE TITLE
initial state widgets forced to sum to 1 even if not appropriate / incorrect error message methodology used

### ISSUE THREAD

**Issue by jarmarshall** [DiODeProject/MuMoT#317]
In `_format_advanced_option()` initial state widgets are forced to sum to 1 without checking if this is appropriate; if the system is not conserved `_constantSystemSize == None` or `== False` then user-provided values should not be altered

Additionally, the warning message is printed; the appropriate way to raise errors such as this is via the `_errorMessage` widget, accessed via `_showErrorMessage()`

**Comment by joefresna** [comment]
Problem with exceptions and warnings has a dedicated issue #352
