### ISSUE TITLE
Some rates are not properly handled in some models... probably a parser issue

### ISSUE THREAD

**Issue by joefresna** [DiODeProject/MuMoT#321]
Some models (e.g. attached example) do not work properly because one rate is not visualised among the free parameters. It forces the user to fix the rate (via `params` option) in order to avoid mumot to crash.
[issue_missing_variable.zip](https://github.com/DiODeProject/MuMoT/files/3321892/issue_missing_variable.zip)

**Comment by jarmarshall** [comment]
Same root cause and hence solution as #322
