### ISSUE TITLE
Only define versions in one place (using setuptools-scm)

### ISSUE THREAD

**Issue by willfurnass** [DiODeProject/MuMoT#393]
At present MuMoT versions are defined in two places:
 - annotated tags in Git 
 - `mumot/_version.py`

This is somewhat clunky, particularly when creating new releases.

I propose we introduce [setuptools-scm](https://pypi.org/project/setuptools-scm/) as a build-time dependency, which inserts version info into a wheel or source distribution using the info from `git describe` (based in part on git tags).  We could then remove `mumot/_version.py` and all references to it.

**Comment by jarmarshall** [comment]
Sounds sensible to me... - need to check where `about()` pulls its version information from as well...
