### ISSUE TITLE
Erroneous line breaks before some (not all) in-line LaTeX in Markdown cells (Safari only)

### ISSUE THREAD

**Issue by willfurnass** [DiODeProject/MuMoT#397]
Version: 9b00b15b89dda3d0382ffcac8b9f8d1240a010c6 (and probably older too)

Seen by @jarmarshall and @joefresna with Safari.  Not an issue with Firefox or Chrome.

**Comment by willfurnass** [comment]
@jarmarshall @joefresna What MathJax version does the Safari JavaScript console say you're using? Also, do you see the same problem with the `unpin_ipykernel_notebook_pyzmq_tornado` branch in my fork?

**Comment by jarmarshall** [comment]
Sorry, not sure how to check that…

**Comment by willfurnass** [comment]
In Firefox, I can see a log of HTTP(S) requests if I go to the 'hamburger' button -> *Web Developer* -> *Network* then refresh the page.  IIRC MathJax is pulled from a [CDN](https://en.wikipedia.org/wiki/Content_delivery_network) by Jupyter UI code and the MathJax version is in the associated URL.

**Comment by jarmarshall** [comment]
I believe it’s v2.6.0

**Comment by willfurnass** [comment]
With my `unpin_ipykernel_notebook_pyzmq_tornado` branch you should get 2.7.7 instead - do you see the same issue with Safari when running that branch?

**Comment by willfurnass** [comment]
Fixed by #398
