### ISSUE TITLE
bifurcation() causes TypeError: cannot determine truth value of Relational

### ISSUE THREAD

**Issue by joefresna** [DiODeProject/MuMoT#411]
The attached minimal example notebook causes the following error:
`TypeError: cannot determine truth value of Relational`
for the function `bifurcation()`

[issue_bifurcation.ipynb.zip](https://github.com/DiODeProject/MuMoT/files/5559795/issue_bifurcation.ipynb.zip)

**Comment by jarmarshall** [comment]
Need to check which version this is against, as on MyBinder this is apparently working fine...

**Comment by joefresna** [comment]
I found the problem. It did not see an untracked local change. False alarm. Sorry
